/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import classes.Pessoa;
import java.util.*;

/**
 *
 * @author Silvia
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuCadPessoa = new javax.swing.JMenuItem();
        mnuCadEndereco = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuCadEmp = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnuRelatPessoa = new javax.swing.JMenuItem();
        mnuRelatEndereco = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuRelatEmp = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        jMenu4.setText("jMenu4");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Arquivo");

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastros");

        mnuCadPessoa.setText("Pessoa");
        mnuCadPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadPessoaActionPerformed(evt);
            }
        });
        jMenu2.add(mnuCadPessoa);

        mnuCadEndereco.setText("Endereço");
        mnuCadEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadEnderecoActionPerformed(evt);
            }
        });
        jMenu2.add(mnuCadEndereco);
        jMenu2.add(jSeparator1);

        mnuCadEmp.setText("Empregado");
        mnuCadEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadEmpActionPerformed(evt);
            }
        });
        jMenu2.add(mnuCadEmp);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Relatórios");

        mnuRelatPessoa.setText("Pessoa");
        mnuRelatPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRelatPessoaActionPerformed(evt);
            }
        });
        jMenu5.add(mnuRelatPessoa);

        mnuRelatEndereco.setText("Endereço");
        mnuRelatEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRelatEnderecoActionPerformed(evt);
            }
        });
        jMenu5.add(mnuRelatEndereco);
        jMenu5.add(jSeparator2);

        mnuRelatEmp.setText("Empregado");
        mnuRelatEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRelatEmpActionPerformed(evt);
            }
        });
        jMenu5.add(mnuRelatEmp);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCadEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCadEnderecoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mnuCadPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadPessoaActionPerformed
        // TODO add your handling code here:
        new CadPessoa().setVisible(true);
    }//GEN-LAST:event_mnuCadPessoaActionPerformed

    private void mnuRelatPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRelatPessoaActionPerformed
        // TODO add your handling code here:
        new ListPessoa().setVisible(true);
    }//GEN-LAST:event_mnuRelatPessoaActionPerformed

    private void mnuCadEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadEmpActionPerformed
        // TODO add your handling code here:
        new CadEmpregado().setVisible(true);
    }//GEN-LAST:event_mnuCadEmpActionPerformed

    private void mnuRelatEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRelatEnderecoActionPerformed
        // TODO add your handling code here:
        new ListEndereco().setVisible(true);
    }//GEN-LAST:event_mnuRelatEnderecoActionPerformed

    private void mnuRelatEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRelatEmpActionPerformed
        // TODO add your handling code here:
        new ListEmpregado().setVisible(true);
    }//GEN-LAST:event_mnuRelatEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem mnuCadEmp;
    private javax.swing.JMenuItem mnuCadEndereco;
    private javax.swing.JMenuItem mnuCadPessoa;
    private javax.swing.JMenuItem mnuRelatEmp;
    private javax.swing.JMenuItem mnuRelatEndereco;
    private javax.swing.JMenuItem mnuRelatPessoa;
    // End of variables declaration//GEN-END:variables
}
